### ISSUE TITLE
Paper grammar

### ISSUE THREAD

**Issue by kellieotto** [iagolemos1/thresholdmodeling#1]
This is part of your [JOSS review](https://github.com/openjournals/joss-reviews/issues/2013).

I recognize that English might not be your native language. Unfortunately, there are some sentences that are grammatically incorrect and I don't understand the meaning. Below, I will make corrections where I can and point out places where I don't understand the intended meaning. I hope this is helpful!

**first paragraph:** "dealig" --> "dealing", "asymtopic" --> "asymptotic"
**first paragraph:** the last sentence needs to be rewritten as it is not grammatically correct

**second paragraph:** "since the threshold selection until deep statistical analyses" -- I don't know what this means; I think "until" and "since" are the wrong words.

**third paragraph:** "which ones provide" --> "that are used for" ; "which one does not contemple" --> "which does not contain" ; "excesses" --> "many" (?) 

**Model Checking section:** "heoretical" --> "theoretical" ; "provided,using" --> "provided, using"

**Declustering section:** "giving empirical rule" --> "given empirical rule" ; "maximuns" --> "maximums"

**Reproducibility and User's Guide:** "confronting" --> "testing"

**Comment by iagolemos1** [comment]
Thanks, @kellieotto. I am going to consider all the corrections. Some of the errors are lack of attention. I am going to try to rewrite the sentences with grammatical errors.

**Comment by kellieotto** [comment]
The paper is much improved. A few more small grammar edits:

**first paragraph**: "been emerged"-->"emerged" ; "maximums observations"-->"maximum observations"

**second paragraph**: "extremes of dependences sequences" I'm not sure exactly what this phrase means.

**third paragraph**: "into a software context" --> "In software"

**Comment by iagolemos1** [comment]
I made the changes.

**Comment by iagolemos1** [comment]
Thanks :D

**Comment by kellieotto** [comment]
Looks good! Thanks for making all the changes.
