### ISSUE TITLE
R_USER and R_HOME paths

### ISSUE THREAD

**Issue by bahung** [iagolemos1/thresholdmodeling#6]
Installing the POT package will give errors if R_USER and/or R_HOME are not defined in the system environment variables.

Solved by following the guide in [SO](https://stackoverflow.com/questions/12698877/how-to-setup-environment-variable-r-user-to-use-rpy2-in-python):
1. Add R to user path
2. Create R_USER and R_HOME

Please add these to your instalment guideline.

**Comment by iagolemos1** [comment]
Great. I don't know what is this error then. Happy everything is working now. Is your python 2.7?

**Comment by bahung** [comment]
> Great. I don't know what is this error then. Happy everything is working now. Is your python 2.7?

Mine is python 3.7 in Windows with R-Studio and R already installed.

**Comment by iagolemos1** [comment]
I don't reconize this error though. I installed this package in severous machines and didn't get it. By the way, it looks like an ```rpy2``` particular error. Thanks!
